[package]
name = "locutus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
glob = "0.3.0"
ini = "1.3.0"
serde_json = "1.0.81"
